### ISSUE TITLE
flutter_shu_epub

### ISSUE THREAD

**Issue by yoni1988** [getBoolean/shu_epub#16]
Hello，Have you completed the project flutter_shu_epub you mentioned in the Readme? Will this project be open source?
 I am also making the function of epub reader, how to implement horizontal paging of text or Image on the display book, do you have any suggestions?

**Comment by getBoolean** [comment]
Its not finished yet, I have been busy with college, and now an internship. shu_epub is still unfinished, so I haven't started on flutter_shu_epub. shu_epub is maybe half done. Currently shu_epub is able to read all the information about the epub needed to navigate it, but parsing/providing the actual content isn't implemented. I also need to write the CFI generator for shu_epub.

Though unfinished, I've also started experimenting with a paged html reader [here](https://github.com/BookAdapterTeam/book_adapter/tree/main/packages/paged_html). I have some concerns about performance, and it doesn't support selecting the text due to flutter limitations. I'm also not sure how to make it work with jump-to links without needing to render all pages and cache the page number for every line. You can use this for reference for anything you want. (I don't think this approach will work for what I want, which is why its unfinished)

TBH it would probably be better to go native for the html rendering part instead of flutter, though I haven't done enough research into how to make a paged html reader on native android.

**Comment by getBoolean** [comment]
For reference, [iridium](https://github.com/Mantano/iridium) has implemented a horizontal html reader using a webview, though I've found their scrolling to be a little weird.

**Comment by yoni1988** [comment]
> For reference, [iridium](https://github.com/Mantano/iridium) has implemented a horizontal html reader using a webview, though I've found their scrolling to be a little weird.
Thank you, I know this project, but it doesn't scroll smoothly and doesn't support epub3 very well.

**Comment by yoni1988** [comment]
I know you are Chinese, can I add you on WeChat?

**Comment by getBoolean** [comment]
> I know you are Chinese, can I add you on WeChat?

I don't use WeChat, ~~but I do have Discord. I have added my username in my bio~~

**Comment by getBoolean** [comment]
> I know you are Chinese, can I add you on WeChat?

I changed my mind on Discord, I don't like accepting friend requests there. You can message me at my new twitter account [@getBoolean](https://twitter.com/getBoolean)
